import React from 'react'
import Head from 'next/head'
import axios from 'axios'

import { Inter } from '@next/font/google'
import { withLayout } from '@/layout/Layout'
import { Button, Htag, P, Rating, Tag } from '@/components'

import type { GetStaticProps } from 'next'
import type { MenuItem } from '@/interfaces/menu.interface'

const inter = Inter({ subsets: ['latin'] })

function Home({ menu, firstCategory }: HomeProps): JSX.Element {
  const [rating, setRating] = React.useState<number>(4)

  return (
    <>
      <Head>
        <title>First Next Test</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main>
        <>
          <Htag tag='h1'>Text</Htag>
          <Button apperance='primary' arrow='down'>
            textButton
          </Button>
          <Button apperance='ghost' arrow='right'>
            textButtonGhost
          </Button>
          <P size='l'>large</P>
          <P size='m'>medium</P>
          <P size='s'>small</P>
          <Tag size='s' color='primary'>
            Tag
          </Tag>

          <Rating rating={rating} setRating={setRating} isEditable />
          <ul>
            {menu.map(m => (
              <li key={m._id.secondCategory}>{m._id.secondCategory}</li>
            ))}
          </ul>
        </>
      </main>
    </>
  )
}

export default withLayout(Home)

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const firstCategory = 0
  const { data: menu } = await axios.post<MenuItem[]>(
    process.env.NEXT_PUBLIC_DOMAIN + '/api/top-page/find',
    {
      firstCategory,
    }
  )
  return {
    props: {
      menu,
      firstCategory,
    },
  }
}

interface HomeProps extends Record<string, unknown> {
  menu: MenuItem[]
  firstCategory: number
}
