import React from 'react'
import Head from 'next/head'

import { Inter } from '@next/font/google'
import { Button, Htag, P, Rating, Tag } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [rating, setRating] = React.useState<number>(4)

  return (
    <>
      <Head>
        <title>First Next Test</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main>
        <Htag tag='h1'>Text</Htag>
        <Button apperance='primary' arrow='down'>
          textButton
        </Button>
        <Button apperance='ghost' arrow='right'>
          textButtonGhost
        </Button>
        <P size='l'>large</P>
        <P size='m'>medium</P>
        <P size='s'>small</P>
        <Tag size='s' color='primary'>
          Tag
        </Tag>

        <Rating rating={rating} setRating={setRating} isEditable />
      </main>
    </>
  )
}
